fp_ret: .branchtargets
        retg1p_dbl_0,
#define retg1p_dbl_0_          0
        retg1p_dbl_1,
#define retg1p_dbl_1_          1
        retg1p_dbl_2,
#define retg1p_dbl_2_          2
        retg1p_dbl_3,
#define retg1p_dbl_3_          3
        retg1p_dbl_4,
#define retg1p_dbl_4_          4
        retg1p_dbl_5,
#define retg1p_dbl_5_          5
        retg1p_dbl_6,
#define retg1p_dbl_6_          6
        retg1p_dbl_7,
#define retg1p_dbl_7_          7
        retg1p_dbl_8,
#define retg1p_dbl_8_          8
        retg1p_dbl_9,
#define retg1p_dbl_9_          9
        retg1p_dbl_10,
#define retg1p_dbl_10_        10
        retg1p_dbl_11,
#define retg1p_dbl_11_        11
        retg1p_dbl_12,
#define retg1p_dbl_12_        12
        retg1p_dbl_13,
#define retg1p_dbl_13_        13
        retg1p_dbl_14,
#define retg1p_dbl_14_        14
        retg1p_dbl_15,
#define retg1p_dbl_15_        15
        retg1p_dbl_16,
#define retg1p_dbl_16_        16
        retg1p_dbl_17;
#define retg1p_dbl_17_        17
