fp_ret: .branchtargets
        retg1p_dbl_0,
#define retg1p_dbl_0_          0
        retg1p_dbl_1,
#define retg1p_dbl_1_          1
        retg1p_dbl_2,
#define retg1p_dbl_2_          2
        retg1p_dbl_3,
#define retg1p_dbl_3_          3
        retg1p_dbl_4,
#define retg1p_dbl_4_          4
        retg1p_dbl_5,
#define retg1p_dbl_5_          5
        retg1p_dbl_6,
#define retg1p_dbl_6_          6
        retg1p_dbl_7,
#define retg1p_dbl_7_          7
        retg1p_dbl_8,
#define retg1p_dbl_8_          8
        retg1p_dbl_9,
#define retg1p_dbl_9_          9
        retg1p_dbl_10,
#define retg1p_dbl_10_        10
        retg1p_dbl_11,
#define retg1p_dbl_11_        11
        retg1p_dbl_12,
#define retg1p_dbl_12_        12
        retg1p_dbl_13,
#define retg1p_dbl_13_        13
        retg1p_dbl_14,
#define retg1p_dbl_14_        14
        retg1p_dbl_15,
#define retg1p_dbl_15_        15
        retg1p_dbl_16,
#define retg1p_dbl_16_        16
        retg1p_dbl_17,
#define retg1p_dbl_17_        17
        retg1p_add_0,
#define retg1p_add_0_         18
        retg1p_add_1,
#define retg1p_add_1_         19
        retg1p_add_2,
#define retg1p_add_2_         20
        retg1p_add_3,
#define retg1p_add_3_         21
        retg1p_add_4,
#define retg1p_add_4_         22
        retg1p_add_5,
#define retg1p_add_5_         23
        retg1p_add_6,
#define retg1p_add_6_         24
        retg1p_add_7,
#define retg1p_add_7_         25
        retg1p_add_8,
#define retg1p_add_8_         26
        retg1p_add_9,
#define retg1p_add_9_         27
        retg1p_add_10,
#define retg1p_add_10_        28
        retg1p_add_11,
#define retg1p_add_11_        29
        retg1p_add_12,
#define retg1p_add_12_        30
        retg1p_add_13,
#define retg1p_add_13_        31
        retg1p_add_14,
#define retg1p_add_14_        32
        retg1p_add_15,
#define retg1p_add_15_        33
        retg1p_add_16,
#define retg1p_add_16_        34
        retg1p_add_17,
#define retg1p_add_17_        35
        retg1p_add_18,
#define retg1p_add_18_        36
        retg1p_add_19,
#define retg1p_add_19_        37
        retg1p_add_20,
#define retg1p_add_20_        38
        retg1p_add_21,
#define retg1p_add_21_        39
        retg1p_add_22,
#define retg1p_add_22_        40
        retg1p_add_23,
#define retg1p_add_23_        41
        retg1p_add_24,
#define retg1p_add_24_        42
        retg1p_add_25,
#define retg1p_add_25_        43
        retg1p_add_26,
#define retg1p_add_26_        44
        retg1p_add_27,
#define retg1p_add_27_        45
        retg1p_add_28,
#define retg1p_add_28_        46
        retg1p_add_29,
#define retg1p_add_29_        47
        retg1p_add_30,
#define retg1p_add_30_        48
        retg1p_add_31,
#define retg1p_add_31_        49
        retg1p_add_32,
#define retg1p_add_32_        50
        retg1p_add_33,
#define retg1p_add_33_        51
        retg1p_addsub_0,
#define retg1p_addsub_0_      52
        retg1p_addsub_1,
#define retg1p_addsub_1_      53
        retg1p_addsub_2,
#define retg1p_addsub_2_      54
        retg1p_addsub_3,
#define retg1p_addsub_3_      55
        retg1p_addsub_4,
#define retg1p_addsub_4_      56
        retg1p_addsub_5,
#define retg1p_addsub_5_      57
        retg1p_addsub_6,
#define retg1p_addsub_6_      58
        retg1p_addsub_7,
#define retg1p_addsub_7_      59
        retg1p_addsub_8,
#define retg1p_addsub_8_      60
        retg1p_addsub_9,
#define retg1p_addsub_9_      61
        retg1p_addsub_10,
#define retg1p_addsub_10_     62
        retg1p_addsub_11,
#define retg1p_addsub_11_     63
        retg1p_addsub_12,
#define retg1p_addsub_12_     64
        retg1p_addsub_13,
#define retg1p_addsub_13_     65
        retg1p_addsub_14,
#define retg1p_addsub_14_     66
        retg1p_addsub_15,
#define retg1p_addsub_15_     67
        retg1p_addsub_16,
#define retg1p_addsub_16_     68
        retg1p_addsub_17,
#define retg1p_addsub_17_     69
        retg1p_addsub_18,
#define retg1p_addsub_18_     70
        retg1p_addsub_19,
#define retg1p_addsub_19_     71
        retg1p_addsub_20,
#define retg1p_addsub_20_     72
        retg1p_addsub_21,
#define retg1p_addsub_21_     73
        retg1p_addsub_22,
#define retg1p_addsub_22_     74
        retg1p_addsub_23,
#define retg1p_addsub_23_     75
        retg1p_addsub_24,
#define retg1p_addsub_24_     76
        retg1p_addsub_25,
#define retg1p_addsub_25_     77
        retg1p_addsub_26,
#define retg1p_addsub_26_     78
        retg1p_addsub_27,
#define retg1p_addsub_27_     79
        retg1p_addsub_28,
#define retg1p_addsub_28_     80
        retg1p_addsub_29,
#define retg1p_addsub_29_     81
        retg1p_addsub_30,
#define retg1p_addsub_30_     82
        retg1p_addsub_31,
#define retg1p_addsub_31_     83
        retg1p_addsub_32,
#define retg1p_addsub_32_     84
        retg1p_addsub_33,
#define retg1p_addsub_33_     85
        retg1p_addsub_34,
#define retg1p_addsub_34_     86
        retg1p_addsub_35,
#define retg1p_addsub_35_     87
        retg1p_addsub_36,
#define retg1p_addsub_36_     88
        retg1p_addsub_37,
#define retg1p_addsub_37_     89
        retg1p_addsub_38,
#define retg1p_addsub_38_     90
        retg1p_addsub_39,
#define retg1p_addsub_39_     91
        retg1p_addsub_40,
#define retg1p_addsub_40_     92
        retg1p_addsub_41,
#define retg1p_addsub_41_     93
        retg1p_addsub_42,
#define retg1p_addsub_42_     94
        retg1p_addsub_43,
#define retg1p_addsub_43_     95
        retg1p_addsub_44,
#define retg1p_addsub_44_     96
        retg1p_addsub_45,
#define retg1p_addsub_45_     97
        retg1p_addsub_46,
#define retg1p_addsub_46_     98
        retg1p_addsub_47,
#define retg1p_addsub_47_     99
        retg1p_addsub_48,
#define retg1p_addsub_48_    100
        retg1p_addsub_49,
#define retg1p_addsub_49_    101
        retg1p_addsub_50;
#define retg1p_addsub_50_    102
